### ISSUE TITLE
replicas_on_same replicas_on_different stopped working

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-csi#31]
Hi, my storageClass:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-a-b
parameters:
  ReplicasOnDifferent: side
  ReplicasOnSame: moonshot
  autoPlace: "2"
  storagePool: thindata
provisioner: linstor.csi.linbit.com
```

Provisioner runs:

```
curl -X 'POST' -d '{"select_filter":{"place_count":2,"storage_pool":"thindata","replicas_on_same":["moonshot"],"replicas_on_different":["side"]},"layer_list":["DRBD","STORAGE"]}' -H 'Accept: application/json' -H 'Content-Type: application/json' 'http://localhost:3370/v1/resource-definitions/pvc-01a17976-a143-4c31-b118-3bcccb7951e5/autoplace'
```

but correct commad is:
```
curl -X 'POST' -d '{"select_filter":{"place_count":2,"storage_pool":"thindata","replicas_on_same":["Aux/moonshot"],"replicas_on_different":["Aux/side"]},"layer_list":["DRBD","STORAGE"]}' -H 'Accept: application/json' -H 'Content-Type: application/json' 'http://localhost:3370/v1/resource-definitions/pvc-01a17976-a143-4c31-b118-3bcccb7951e5/autoplace'
```

version:
```
image: quay.io/linbit/linstor-csi:v0.7.2
```
