### ISSUE TITLE
snapshot permissions need to be updated and example manifest snapshotter to reflect new naming convention

### ISSUE THREAD

**Issue by JSimon000** [LINBIT/linstor-csi#45]
Perhaps on related to kubernetes 1.15.0+ but this one took me a while to get working because the driver name in the example manifests is wrong.

In order to get this working I had to first change the snapshotter to:
```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1alpha1
metadata:
  annotations:
    k10.kasten.io/is-snapshot-class: "true" # required for kasten.io to use the snapshot class
  name: linstor-csi-snapshot-class
  namespace: kube-system
snapshotter: linstor.csi.linbit.com
```

and once I got that working I finally got some action in the csi-snapshotter logs and received an error related to a permission for the volumesnapshots/status api. Additionally reference the official csi manifest I also added the "update" verb to persistentvolumeclaims resources. my linstor-csi-snapshotter-role looks like this:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linstor-csi-snapshotter-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update"]
```

after doing this snapshots are finally working.

Hope this helps :)
